### ISSUE TITLE
这是什么错误？通过gradle导入的包

### ISSUE THREAD

**Issue by SoldierYu** [alibaba/Tangram-Android#102]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.guanfu.app, PID: 7463
                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tmall/wireless/tangram/view/BannerView;
                                                                  at com.tmall.wireless.tangram.TangramBuilder.installDefaultRegistry(TangramBuilder.java:296)
                                                                  at com.tmall.wireless.tangram.TangramBuilder.newInnerBuilder(TangramBuilder.java:360)

**Comment by WayneLyn** [comment]
同样的错误，新建了一个空项目，通过gradle导入。使用后运行出现这个问题。只依赖了recyclerview、fresco和tangram

**Comment by MikeAfc** [comment]
@WayneLyn 看下文档，最新版本有些变动，https://github.com/alibaba/Tangram-Android/blob/master/docs/Tutorial-ch.md

// 最新版本引入了rxjava，需要自行添加rx依赖
compile 'io.reactivex.rxjava2:rxjava:2.1.12'
compile 'io.reactivex.rxjava2:rxandroid:2.0.2'

**Comment by princeHe** [comment]
遇到了同样的问题，完全按照文档配置，一样无法使用，问题也是NoClassDefFoundError
