### ISSUE TITLE
混淆后无法使用

### ISSUE THREAD

**Issue by aliang5820** [alibaba/Tangram-Android#139]
按照之前找到的issues里，加入了vlayout的混淆规则，但是在我这里还是没有用
`java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class android.content.Context]
        at com.tmall.wireless.tangram.structure.d.a(ViewCreator.java:74)
        at com.tmall.wireless.tangram.structure.d.a(ViewCreator.java:65)
        at com.tmall.wireless.tangram.b.a.b.a(BaseCellBinder.java:79)
        at com.tmall.wireless.tangram.b.a.l.a(PojoGroupBasicAdapter.java:124)
        at com.tmall.wireless.tangram.a.a.c.a(GroupBasicAdapter.java:297)
        at com.tmall.wireless.tangram.a.a.c.onCreateViewHolder(GroupBasicAdapter.java:60)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$c.a(ExposeLinearLayoutManagerEx.java:1628)
        at com.alibaba.android.vlayout.VirtualLayoutManager$e.a(VirtualLayoutManager.java:1114)
        at com.alibaba.android.vlayout.a.n.b(RangeGridLayoutHelper.java:346)
        at com.alibaba.android.vlayout.a.b.a(BaseLayoutHelper.java:318)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:706)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1161)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:504)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16636)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:16636)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16636)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16636)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16636)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16636)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16636)`

**Comment by shenshizhong** [comment]
请求这个问题解决了么，怎么处理的呢
