### ISSUE TITLE
tangram:3.1.9.5 集成到项目一直报错

### ISSUE THREAD

**Issue by shenshizhong** [alibaba/Tangram-Android#145]
java.lang.NoSuchMethodException: <init> [class android.content.Context]
        at bvi.a(SourceFile:74)
        at bvi.a(SourceFile:65)
        at bug.a(SourceFile:79)
        at buq.a(SourceFile:124)
        at btt.c(SourceFile:297)
        at btt.a(SourceFile:60)
        at android.support.v7.widget.RecyclerView$a.b(SourceFile:6685)

请问这个是怎么回事呢？谢谢

**Comment by MikeAfc** [comment]
贴下反混淆后的堆栈

shenshizhong <notifications@github.com> 于2019年1月29日周二 下午10:25写道：

**Comment by shenshizhong** [comment]
日志：
java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class android.content.Context]
        at bvg.a(SourceFile:74)
        at bvg.a(SourceFile:65)
        at bue.a(SourceFile:79)
        at buo.a(SourceFile:124)
        at btr.c(SourceFile:297)
        at btr.a(SourceFile:60)
        at android.support.v7.widget.RecyclerView$a.b(SourceFile:6685)
        at android.support.v7.widget.RecyclerView$n.a(SourceFile:5869)
        at android.support.v7.widget.RecyclerView$n.a(SourceFile:5752)
        at android.support.v7.widget.RecyclerView$n.c(SourceFile:5748)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$c.a(SourceFile:1628)
        at com.alibaba.android.vlayout.VirtualLayoutManager$e.a(SourceFile:1114)
        at od.a(SourceFile:116)
        at ol.b(SourceFile:92)
        at od.a(SourceFile:318)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(SourceFile:706)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(SourceFile:1161)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(SourceFile:365)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(SourceFile:504)
        at android.support.v7.widget.RecyclerView.N(SourceFile:3812)
        at android.support.v7.widget.RecyclerView.q(SourceFile:3529)
        at android.support.v7.widget.RecyclerView.onLayout(SourceFile:4082)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
        at android.view.View.layout(View.java:16653)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2198)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1958)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
        at android.view.Choreographer.doFrame(Choreographer.java:608)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:5524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

防止混淆：
-keepattributes InnerClasses
-keep class com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutParams { *; }
-keep class android.support.v7.widget.RecyclerView$ViewHolder { *; }
-keep class android.support.v7.widget.ChildHelper { *; }
-keep class android.support.v7.widget.ChildHelper$Bucket { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutManager { *; }

难道混淆文件写错了？

**Comment by shenshizhong** [comment]
补充： 在 classpath 'com.android.tools.build:gradle:2.3.2' 是没问题，
但如果使用 classpath 'com.android.tools.build:gradle:3.2.1' 就会报类似错误

**Comment by shenshizhong** [comment]
补充：新写了个demo，不混淆没事，一混淆就报上面的错误，怎么感觉混淆没效果呢？

**Comment by shenshizhong** [comment]
问题已经解决了，可以看这个demo：  https://github.com/shenshizhong/TangramDemo

解决方法：加了一个自定义控件的防止混淆就行了。
防止混淆的代码如下：
-dontwarn com.squareup.okhttp.**
-dontwarn com.squareup.picasso.**

-keep class com.tmall.wireless.tangram.** { *;}
-keepattributes InnerClasses
-keep class com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutParams { *; }
-keep class android.support.v7.widget.RecyclerView$ViewHolder { *; }
-keep class android.support.v7.widget.ChildHelper { *; }
-keep class android.support.v7.widget.ChildHelper$Bucket { *; }
-keep class android.support.v7.widget.RecyclerView$LayoutManager { *; }

# keep自定义view及其构造方法、set方法
-keep public class * extends android.view.View {
      public <init>(android.content.Context);
      public <init>(android.content.Context, android.util.AttributeSet);
      public <init>(android.content.Context, android.util.AttributeSet, int);
      public void set*(...);
}


可算解决了，可以过个好年啦，祝大家新年快乐~

**Comment by caldremch** [comment]
加了 vlayout 和 tangram的混淆,再加这个
-keepclasseswithmembers class * { 
   public <init>(android.content.Context);
}
