### ISSUE TITLE
container-banner 组件设置setCells 之后报错

### ISSUE THREAD

**Issue by WhiteorBlack** [alibaba/Tangram-Android#149]
如果json文件中的items size 与之后setCells 的 数据size不一致会报如下错误
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1200, found: 800 Pager id: com.lixin.amuseadjacent:id/TANGRAM_BANNER_ID Pager class: class com.tmall.wireless.tangram.view.BannerViewPager Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1137)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at com.tmall.wireless.tangram.view.BannerViewPager.onMeasure(BannerViewPager.java:75)
        at android.view.View.measure(View.java:20009)
        at com.tmall.wireless.tangram.view.BannerView.onMeasure(BannerView.java:384)
        at android.view.View.measure(View.java:20009)
        at com.alibaba.android.vlayout.VirtualLayoutManager.measureChildWithDecorationsAndMargin(VirtualLayoutManager.java:1505)
        at com.alibaba.android.vlayout.VirtualLayoutManager.measureChildWithMargins(VirtualLayoutManager.java:1322)
        at com.alibaba.android.vlayout.layout.LinearLayoutHelper.layoutViews(LinearLayoutHelper.java:164)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:739)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1161)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:374)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:530)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at in.srain.cube.views.ptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:260)
        at in.srain.cube.views.ptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:229)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
2019-03-15 14:45:46.030 27512-27512/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:759)
        at android.view.View.layout(View.java:17789)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2372)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1276)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6483)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:888)
        at android.view.Choreographer.doCallbacks(Choreographer.java:700)
        at android.view.Choreographer.doFrame(Choreographer.java:635)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:874)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6381)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

**Comment by WhiteorBlack** [comment]
自己的解决方法是 使用 TangramEngine 中的replaceCells(Card,List<BaseCell>)方法代替 setCells()方法
