### ISSUE TITLE
int android.view.View.getId()

### ISSUE THREAD

**Issue by 1982582704** [alibaba/Tangram-Android#186]
Process: com.zadh.industry, PID: 585
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
        at com.tmall.wireless.tangram.dataparser.concrete.BaseCellBinder.createView(BaseCellBinder.java:83)
        at com.tmall.wireless.tangram.dataparser.concrete.PojoGroupBasicAdapter.createViewHolder(PojoGroupBasicAdapter.java:124)
        at com.tmall.wireless.tangram.core.adapter.GroupBasicAdapter.onCreateViewHolder(GroupBasicAdapter.java:297)
        at com.tmall.wireless.tangram.core.adapter.GroupBasicAdapter.onCreateViewHolder(GroupBasicAdapter.java:60)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx$LayoutState.next(ExposeLinearLayoutManagerEx.java:1628)
        at com.alibaba.android.vlayout.VirtualLayoutManager$LayoutStateWrapper.next(VirtualLayoutManager.java:1143)
        at com.alibaba.android.vlayout.layout.RangeGridLayoutHelper.layoutViews(RangeGridLayoutHelper.java:372)
        at com.alibaba.android.vlayout.layout.BaseLayoutHelper.doLayout(BaseLayoutHelper.java:318)
        at com.alibaba.android.vlayout.VirtualLayoutManager.layoutChunk(VirtualLayoutManager.java:741)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.fill(ExposeLinearLayoutManagerEx.java:1161)
        at com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx.onLayoutChildren(ExposeLinearLayoutManagerEx.java:365)
        at com.alibaba.android.vlayout.VirtualLayoutManager.onLayoutChildren(VirtualLayoutManager.java:536)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2727)
        at android.view.View.layout(View.java:16673)
        at android.view.ViewGroup.layout(ViewGroup.java:5476)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2304)
    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2

**Comment by 1982582704** [comment]
为什么导不了 “com.tmall.wireless.tangram.core.adapter.GroupBasicAdapter”这个包呢？
